日報の言及機能を作る
jun-kondo/fjord-books_app-2023 pull request #7
Opened 2024-03-29 10:32 UTC by jun-kondo

お疲れ様です。
日報の言及機能を作る プラクティスの課題を提出致します。
レビューよろしくお願いします🙇‍♂️

## 概要
Booksアプリに日報の言及機能を実装しました。

## RuboCop結果

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFo1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f07ba6b9a8609510ca891fe4c861843596d600fe/image.png)

## ERBLint結果

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGQ1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f005f62f05536fd990e22223efe358b57fdbe00b/image.png)

## 言及機能
### 新規作成時
本文にURLが含まれていると、言及先の日報の詳細ページに言及元の日報のタイトルとリンクが表示される。
|  本文のreports/55のURLを含めて作成 | 言及先ページのリンクから言及元に移動  |
| :---: | :---:| 
| [![Image from Gyazo](https://i.gyazo.com/f228b37d6f57a17d2e197a82827975b3.gif)](https://gyazo.com/f228b37d6f57a17d2e197a82827975b3) | [![Image from Gyazo](https://i.gyazo.com/bfb9cc0df9c9b6350a806e25d87972de.gif)](https://gyazo.com/bfb9cc0df9c9b6350a806e25d87972de)

### 更新時
本文内から日報のURLが消えると、言及先の日報のページからも言及表示が削除される。
|  本文のreports/55のURLを削除して更新 |  reports/55に移動  |
| :---: | :---:| 
| [![Image from Gyazo](https://i.gyazo.com/4c5f1eccfc883140cea63f9d1f04cb8b.gif)](https://gyazo.com/4c5f1eccfc883140cea63f9d1f04cb8b) | [![Image from Gyazo](https://i.gyazo.com/11459a98b1d3b6275eacd84d402c061e.gif)](https://gyazo.com/11459a98b1d3b6275eacd84d402c061e) |

### 削除時
本文にURLを含む日報を削除した場合、言及先の日報のページからも言及表示が削除される。
|  本文のreports/55のURLを含む日報を削除 |  reports/55に移動  |
| :---: | :---:| 
| [![Image from Gyazo](https://i.gyazo.com/04c5e51a6577e389e95351e2ab4e46d7.gif)](https://gyazo.com/04c5e51a6577e389e95351e2ab4e46d7) | [![Image from Gyazo](https://i.gyazo.com/89a3cd37144e67727e6328c9d28dc3c7.gif)](https://gyazo.com/89a3cd37144e67727e6328c9d28dc3c7) |

2024-04-04 15:51 UTC, u1tnk requested changes

2024-04-04 15:51 UTC, u1tnk commented on app/models/report.rb
> +    return if other_report.blank?
メソッドにしたことでblankのチェックと自分では無いチェックが発生していてシンプルでは無くなっているのでメソッドにする必要は無いんじゃないかと思います。
あと、`Mention` クラスがあるときに `mention` というメソッドを見ると associationかな？って思うところもちょっと微妙です。

2024-04-04 15:51 UTC, u1tnk commented on app/models/report.rb
> +  def save_mentioning_reports
mentioning_reportsがassociationにあるのでこの名前だと associationをsaveするだけのように見えるので名前を検討お願いします 🙏

2024-04-04 15:51 UTC, u1tnk commented on app/controllers/reports_controller.rb
> +      @report.save_mentioning_reports
saveが実行されたあとにここに来ますが、ここで失敗したときに不整合が起きてしまいます。「トランザクション」で調べてみてください。

2024-04-04 15:51 UTC, u1tnk commented on app/controllers/reports_controller.rb
> +      @report.save_mentioning_reports
こちらもトランザクションの対応が必要になります。

2024-04-04 19:48 UTC, jun-kondo commented on app/models/report.rb
> +    return if other_report.blank?
メソッドを削除し、呼び出し元に移動させました。
> あと、Mention クラスがあるときに mention というメソッドを見ると associationかな？って思うところもちょっと微妙です。

確かに`report.mention`て書いてあったらアソシエーション先のレコードを呼び出してる感じになっちゃいますね。。。
https://github.com/jun-kondo/fjord-books_app-2023/pull/7/commits/d71695d6f435109bc918428438a41386a4dd55a2

2024-04-04 19:52 UTC, jun-kondo commented on app/models/report.rb
> +  def save_mentioning_reports
Mentionのレコードを保存するので、`save_mentions`に変更しました。
https://github.com/jun-kondo/fjord-books_app-2023/pull/7/commits/f69cfe0fc9b38a51552abb1f52f7796be8cf5c08

2024-04-04 19:58 UTC, jun-kondo commented on app/controllers/reports_controller.rb
> +      @report.save_mentioning_reports
コントローラでの呼び出しを削除し、Reportモデルに`after_save :save_mentions`でコールバックを使うようにしました。
コールバックで呼び出したメソッドで例外が発生した場合、`save`, `update`のトランザクションがロールバックされるので不整合を防止できる、との理解ですが如何でしょうか？
https://github.com/jun-kondo/fjord-books_app-2023/pull/7/commits/ada9bba681ca62346821832892fa4d029b2cd6dc

2024-04-04 20:01 UTC, jun-kondo commented on app/controllers/reports_controller.rb
> +      @report.save_mentioning_reports
こちらも`save`時と同様に`after_save`で言及関係を保存する処理を呼び出すようにしました。
https://github.com/jun-kondo/fjord-books_app-2023/pull/7/commits/ada9bba681ca62346821832892fa4d029b2cd6dc

2024-04-04 20:03 UTC, jun-kondo commented
@u1tnk 
レビュー&コメントありがとうございます。
修正してコメント返信致しました!!
引き続きよろしくお願い致します🙇‍♂️

2024-04-05 05:50 UTC, u1tnk commented on app/models/report.rb
> +  def save_mentioning_reports
mentionsも has_manyで有り得る名前なので再検討お願いします。
 save_xxx_mentions と説明を入れるようにすると良いかと思います。

2024-04-05 05:51 UTC, u1tnk commented on app/controllers/reports_controller.rb
> +      @report.save_mentioning_reports
はい、その理解で大丈夫です 🙆‍♀️

2024-04-05 05:51 UTC, u1tnk requested changes
あとは名前のところだけ対応お願いします 🙏

2024-04-06 00:19 UTC, jun-kondo commented on app/models/report.rb
> +  def save_mentioning_reports
命名難しいです😿
日報の言及なので`save_report_mentions`でしょうか？
もしくは日報の本文に含まれる言及を保存するので`save_included_mentions`はどうでしょうか？

2024-04-07 02:16 UTC, jun-kondo commented on app/models/report.rb
> +  def save_mentioning_reports
こちら修正しました!!
https://github.com/jun-kondo/fjord-books_app-2023/pull/7/commits/6bb92e3c28d7ee4f504edd6c96b11bd232f8d7e2

2024-04-07 02:17 UTC, jun-kondo commented
メソッド名のところ修正致しました!!
https://github.com/jun-kondo/fjord-books_app-2023/pull/7#discussion_r1554797764

2024-04-07 07:53 UTC, u1tnk approved these changes

2024-04-08 05:18 UTC, merged